mongo:
  image: mongo
  volumes:
    - /data/mongodb/db:/data/db
  ports:
    - "27017:27017"
    
# agarmans:
#   build: .
#   links:
#     - mongo
#   ports:
#     - "3000:3000"
#   environment:
#     - MONGODB_URI=mongodb://mongo/agarmans
